name: Verify Sample Projects
on: [push, pull_request]
env:
  JHI_E2E_HEADLESS: true
permissions:
  contents: read
jobs:
  samples:
    name: ${{ matrix.app-type }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/app
    if: >-
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.pull_request.title, '[skip ci]') &&
      !contains(github.event.pull_request.title, '[ci skip]') &&
      (github.event.pull_request.draft == false || !contains(github.event.pull_request.labels.*.name, 'pr: skip-ci'))
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        app-type:
          - gradle-jwt-react
          - mvn-jwt-angular
          - mvn-jwt-redis-angular
          - mvn-no-client
          - mvn-oauth-angular
          - gradle-oauth-angular
          - mvn-ms-consul-jwt
          - gradle-ms-eureka-oauth
          - jdl-default-app
    steps:
      - uses: actions/checkout@v4
        with:
          path: generator-jhipster-micronaut
          fetch-depth: 2
      - uses: actions/checkout@v4
        with:
          repository: jhipster/generator-jhipster
          ref: v8.0.0
          path: generator-jhipster
      - name: 'SETUP: environment'
        id: setup
        uses: ./generator-jhipster/.github/actions/setup
        with:
          jdl-sample: ${{ matrix.app-type }}
          application-environment: dev
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.setup.outputs.node-version }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 'Install blueprint'
        run: npm install && npm link
        working-directory: ${{ github.workspace }}/generator-jhipster-micronaut
      - name: 'Generate Project'
        run: mhipster generate-sample ${{ matrix.app-type }} --skip-jhipster-dependencies --force
      - name: 'Start Dependency Containers'
        run: npm run ci:e2e:prepare
      - name: 'Run Server Tests'
        run: npm run ci:backend:test
      - name: 'Run Client Tests'
        run: npm run ci:frontend:test --if-present
      - name: 'Build App'
        run: npm run ci:e2e:package
      - name: 'E2E Tests'
        run: npm run ci:e2e:run --if-present
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
